In [ ]:
import numpy as np

In [ ]:
S_G = np.array([
[1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0]
])

In [ ]:
An = S_G[:,0:13]

In [ ]:
print(An)

[[1 0 0 1 1 0 0 1 1 0 1 0 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 0 0 0]
 [0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [ ]:
Bn = S_G[:,13:26]

In [ ]:
print(Bn)

[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 1 0 0 1 1 0 1 0 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 0 0 0]
 [0 0 1 1 1 1 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 1 0 0 0 1 1 0 0 0 0]]


In [ ]:
latex = "\\begin{bmatrix}\n" + \
        "\\\\\n".join(" & ".join(map(str, row)) for row in Bn) + \
        "\n\\end{bmatrix}"

print(latex)

\begin{bmatrix}
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 1 & 0 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
1 & 0 & 1 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0\\
0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
1 & 0 & 1 & 1 & 0 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0
\end{bmatrix}


In [ ]:
def swapping(matrix_a, matrix_b, idx, binary=True):
    """
    Exchange the column of index idx in the X-part and the column of the index idx in the Z-part respectively  
    """
    A = np.array(matrix_a)
    B = np.array(matrix_b)
    
    for i in range(len(A)):
        A[i,idx], B[i, idx] = B[i, idx], A[i, idx] 
    return A, B


def swapping_new(matrix_a, matrix_b, idx, jdx, binary=True):
    """
    Exchange the columns of index idx in the X-part and Z-part with the columns of the index jdx in the X-part and Z-part, respectively   
    """
    A = np.array(matrix_a)
    B = np.array(matrix_b)
    
    for i in range(len(A)):
        A[i,idx], A[i, jdx] = A[i, jdx], A[i, idx]
        B[i,idx], B[i, jdx] = B[i, jdx], B[i, idx]
    return A, B


def update_column_by_sum_X(matrix_a, matrix_b, pivot_idx, target_idx, binary=True):
    """
    Updates the target column in two matrices by adding the pivot column to it in the X matrix.
    """
    # Ensure inputs are numpy arrays for vector operations
    A = np.array(matrix_a)
    B = np.array(matrix_b)

    # Perform the addition: Target = Target + Pivot
    A[:, target_idx] = A[:, target_idx] + A[:, pivot_idx]
    B[:, pivot_idx] = B[:, pivot_idx] + B[:, target_idx]

    # Apply modulo 2 if working with bit strings/stabilizers
    if binary:
        A %= 2
        B %= 2

    return A, B


def update_column_by_sum_Z(matrix_a, matrix_b, pivot_idx, target_idx, binary=True):
    """
    Updates the target column in two matrices by adding the pivot column to it in the Z matrix.
    """
    # Ensure inputs are numpy arrays for vector operations
    A = np.array(matrix_a)
    B = np.array(matrix_b)

    # Perform the addition: Target = Target + Pivot
    B[:, target_idx] = B[:, target_idx] + B[:, pivot_idx]
    A[:, pivot_idx] = A[:, pivot_idx] + A[:, target_idx]

    # Apply modulo 2 if working with bit strings/stabilizers
    if binary:
        A %= 2
        B %= 2

    return A, B

# --- Quick Test ---
A = np.array([[1, 0], [1, 1]]) # Column 0: [1, 1], Column 1: [0, 1]
B = np.array([[0, 1], [1, 1]]) # Column 0: [0, 1], Column 1: [1, 1]

# Add Column 0 to Column 1
new_A, new_B = update_column_by_sum_X(A, B, 0, 1)

print("Updated Matrix A (Target Col 1 is now Col 1 + Col 0):\n", new_A)
print("\nUpdated Matrix B (Target Col 1 is now Col 1 + Col 0):\n", new_B)

Updated Matrix A (Target Col 1 is now Col 1 + Col 0):
 [[1 1]
 [1 0]]

Updated Matrix B (Target Col 1 is now Col 1 + Col 0):
 [[1 1]
 [0 1]]


#### Symplectic pairs 

In [ ]:
def pivot_search_symp(A, j, m = 9):
    """
    This function localizes the pivot/control in a given row j of the Z part of the matrix or the X part of the matrix   
    """
    list_cnot = []
    pivot = -1
    for i in range(10): # check if there is a non-zero element to serve as pivot/control
        if A[j,m-i] != 0:
            pivot = m-i
            break
    if pivot != -1: 
        for k in range(pivot):
            if A[j,k] != 0: #create the list of CNOT from [pivot target]
                list_cnot.append([pivot, k])
        if len(list_cnot) == 0:
            list_cnot.append([pivot, pivot]) #create a list [pivot pivot] if there is only one non-zero element in the row
        return list_cnot
    else:
        return pivot


def updateZpart(A, B, row):
    """
    Apply the CNOT reconstructed through the list obtained above, in the Z part and opposite in the X part   
    """
    A_n = A
    B_n = B
    lists = pivot_search_symp(B_n,row) #-1 or a list
    if lists != -1: 
        #print(lists[0][0])
        if lists[0][0] != lists[0][1]:
            for (i, j) in lists:
                A_n, B_n = update_column_by_sum_Z(A_n, B_n, i, j, binary=True)
        return A_n, B_n, 0, lists
    else:
        return -1



def updateXpart(A, B, row):
    """
    Apply the CNOT reconstructed through the list obtained above, in the X part and opposite in the Z part   
    """
    A_n = A
    B_n = B    
    lists = pivot_search_symp(A_n,row) # -1 or a list 
    if lists != -1: #need to apply C-NOT at X-part
        #print(lists)
        if lists[0][0] != lists[0][1]:
            for (i, j) in lists:
                A_n, B_n = update_column_by_sum_X(A_n, B_n, i, j, binary=True)
        return A_n, B_n, lists[0][0], lists
    else:
        return -1


#### Isotropic operators

In [ ]:
def pivot_search_iso(A, j, pivot_list):
    list_cnot = []
    pivot = -1
    for i in range(10):
        if A[j,i] != 0 and i not in pivot_list:
            pivot = i
            break
    if pivot != -1: 
        for k in range(10):
            if k != pivot and A[j,k] != 0: #create the list of CNOT from [pivot target]
                list_cnot.append([pivot, k])
        if len(list_cnot) == 0:
            list_cnot.append([pivot, pivot]) #create a list [pivot pivot] if there is only one non-zero element in the row
        return list_cnot
    else:
        return pivot #list = [pivot target]



def updateZpart_iso(A, B, row, list_pivot_iso):
    """
    Apply the CNOT reconstructed through the list obtained above, in the Z part and opposite in the X part   
    """
    A_n = A
    B_n = B
    lists = pivot_search_iso(B_n,row, list_pivot_iso) #-1 or a list
    if lists != -1: 
        #print(lists[0][0])
        if lists[0][0] != lists[0][1]:
            for (i, j) in lists:
                A_n, B_n = update_column_by_sum_Z(A_n, B_n, i, j, binary=True)
        return A_n, B_n, lists[0][0], lists
    else:
        return -1



def updateXpart_iso(A, B, row, list_pivot_iso):
    """
    Apply the CNOT reconstructed through the list obtained above, in the X part and opposite in the Z part   
    """
    A_n = A
    B_n = B    
    lists = pivot_search_iso(A_n,row, list_pivot_iso) # -1 or a list 
    if lists != -1: #need to apply C-NOT at X-part
        #print(lists)
        if lists[0][0] != lists[0][1]:
            for (i, j) in lists:
                A_n, B_n = update_column_by_sum_X(A_n, B_n, i, j, binary=True)
        return A_n, B_n, lists[0][0], lists
    else:
        return -1

#### Gauge operators 

In [ ]:
def pivot_search_gauge(A, j, pivot_list, m=9):
    list_cnot = []
    pivot = -1
    for i in range(10):
        if A[j,i] != 0 and i not in pivot_list:
            pivot = i
            break
    if pivot != -1: 
        for k in range(10):
            if k != pivot and A[j,k] != 0: #create the list of CNOT from [pivot target]
                list_cnot.append([pivot, k])
        if len(list_cnot) == 0:
            list_cnot.append([pivot, pivot]) #create a list [pivot pivot] if there is only one non-zero element in the row
        return list_cnot
    else:
        return pivot #list = [pivot target]


def updateXpart_gauge(A, B, row, pivots):
    """
    Apply the CNOT reconstructed through the list obtained above, in the X part and opposite in the Z part   
    """
    A_n = A
    B_n = B    
    lists = pivot_search_gauge(A_n,row, pivots) # -1 or a list 
    if lists != -1: #need to apply C-NOT at X-part
        #print(lists)
        if lists[0][0] != lists[0][1]:
            for (i, j) in lists:
                A_n, B_n = update_column_by_sum_X(A_n, B_n, i, j, binary=True)
        return A_n, B_n, lists[0][0], lists
    else:
        return -1

def CNOT_given_pivot(A, j, pivot):
    list_cnot = []
    for k in range(10):
        if k != pivot and A[j,k] != 0: #create the list of CNOT from [pivot target]
            list_cnot.append([pivot, k])
    return list_cnot

### Formatting the gates consiting the encoding 

In [ ]:


def CXC(listing):
    """This function allows to format the output of the CNOT applied from the X part of the parity check matrix"""
    char = ''
    for (i,j) in listing:
        char  = char + '['+str(i+1)+','+str(j+1)+'],'
    return char

def CZC(listing):
    """This function allows to format the output of the CNOT applied from the Z part of the parity check matrix"""
    char = ''
    for (i,j) in listing:
        char  = char + '['+str(j+1)+','+str(i+1)+'],'
    return char

def HC(listing):
    """This function allows to format the output of the Hadamard """
    char = ''
    for i in listing:
        char  =  char + 'H_'+str(i+1)
    return char

def SWAPPC(listing):
    """This function allows to format the output of the SWAPs applied """
    char = ''
    for (i,j) in listing:
        char  = char + '['+str(j+1)+','+str(i+1)+'],'
    return char

In [ ]:
def symplectic(A, B, symp = 3, x_iso = 2, z_iso = 3, gg = 1):
    """
    Perform the operations to obtain the matrix
    """
    A_n = A
    B_n = B
    str_of_all_CNOT = ''
    pivot_list = []
    
    #processing the symplectic operators
    for row in range(symp):
        outX = updateXpart(A_n, B_n, row)
        A_n, B_n = outX[0], outX[1]
        pivot_list.append(outX[2]) #only update for the X no need for the Z side
        str_of_all_CNOT = str_of_all_CNOT + CXC(outX[3])
    for row in range(symp,2*symp):
        outZ = updateZpart(A_n, B_n, row)
        A_n, B_n = outZ[0], outZ[1]
        str_of_all_CNOT = str_of_all_CNOT + CZC(outZ[3])

    #processing isotropic
    for i in range(2*symp, 2*symp+x_iso):
        outX = updateXpart_iso(A_n, B_n, i, pivot_list)
        A_n, B_n = outX[0], outX[1]
        pivot_list.append(outX[2])
        str_of_all_CNOT = str_of_all_CNOT + CXC(outX[3])
    for i in range(2*symp+x_iso, 2*symp+x_iso+z_iso):
        outZ = updateZpart_iso(A_n, B_n, i, pivot_list)
        A_n, B_n = outZ[0], outZ[1]
        pivot_list.append(outZ[2])
        str_of_all_CNOT = str_of_all_CNOT + CZC(outZ[3])
    
    for i in range(2*symp+x_iso+z_iso, 2*symp+x_iso+z_iso+gg):
        outX = updateXpart_gauge(A_n, B_n, i, pivot_list)
        A_n, B_n = outX[0], outX[1]
        pivot_list.append(outX[2])
        str_of_all_CNOT = str_of_all_CNOT + CXC(outX[3])
    t = len(pivot_list) - gg
    
    #  Updating the three last gauge operators
    for row in range(2*symp+x_iso+z_iso+gg,2*symp+x_iso+z_iso+2*gg):
        pivot = pivot_list[t]
        CNOT_list = CNOT_given_pivot(B_n, row ,pivot)
        #print(CNOT_list)
        for (i, j) in CNOT_list:
                A_n, B_n = update_column_by_sum_Z(A_n, B_n, i, j, binary=True)
        str_of_all_CNOT = str_of_all_CNOT + CZC(CNOT_list)
        t = t + 1

    #swapping the qubits
    #SWAPlist = [(4,5), (5, 6), (6, 7), (7, 8), (8, 9), (0,3), (1,6), (6,2), (5,4),(5,6)]
    SWAPlist = [(0, 3),(1, 7),(7, 8),(8, 9),(9, 4),(4, 6),(6, 5),(5, 2)]
    for (i, j) in SWAPlist:
        A_n ,B_n = swapping_new(A_n, B_n, i, j)

    # Applying the Hadamard operations at indices 2 and 3 
    A_n, B_n = swapping(A_n, B_n, 2, binary=True)
    A_n, B_n = swapping(A_n, B_n, 3, binary=True)
    H = [2,3]

    return A_n, B_n, str_of_all_CNOT, SWAPPC(SWAPlist),  HC(H)


In [ ]:
Ai, Bi, CNOT, SWAP, H = symplectic(An, Bn)
print("H_X_init = \n", Ai)
print("\n")
print("H_Z_init = \n",Bi)

H_X_init = 
 [[0 0 0 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]


H_Z_init = 
 [[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0]]


In [ ]:

print("Order of operations to transform the stabilizers to initial stabilizers (indices start at 1):")
print("CNOT operators:", CNOT)
print("SWAP operators:", SWAP)
print("Hadamard operators: ",H)
print("Note: The encoding operator will be inverse of this transformation.")

Order of operations to transform the stabilizers to initial stabilizers (indices start at 1):
CNOT operators: [9,1],[9,4],[9,5],[9,8],[10,2],[10,4],[10,6],[10,8],[5,1],[5,3],[1,9],[4,9],[8,9],[2,10],[4,10],[6,10],[8,10],[1,5],[3,5],[2,3],[2,6],[2,7],[2,8],[1,4],[1,6],[8,7],[4,3],[6,3],[3,6],[8,1],[8,2],[6,8],
SWAP operators: [4,1],[8,2],[9,8],[10,9],[5,10],[7,5],[6,7],[3,6],
Hadamard operators:  H_3H_4
Note: The encoding operator will be inverse of this transformation.
